name = "helpdesk"
main = "src/index.ts"
compatibility_date = "2026-03-01"

[[d1_databases]]
binding = "DB"
database_name = "helpdesk-db"
database_id = "1d1e13b7-3ae7-47b4-8c58-1d7b83f8c531" # set this after creating the D1 database

